### ISSUE TITLE
Uncaught Error: Undefined constant "partsCount"

### ISSUE THREAD

**Issue by amaccuish** [grommunio/grommunio-sync#6]
> 9/01/2023 19:33:59 [ 1393] [FATAL] [xxx@xxx.xxx.xxx] Fatal error: /usr/share/grommunio-sync/lib/utils/g_RFC822.php:474 - Uncaught Error: Undefined constant "partsCount" in /usr/share/grommunio-sync/lib/utils/g_RFC822.php:474
> Stack trace:
> #0 /usr/share/grommunio-sync/lib/utils/g_RFC822.php(449): Mail_RFC822->_hasUnclosedBracketsSub('conkergardening...', 0, '<')
> #1 /usr/share/grommunio-sync/lib/utils/g_RFC822.php(375): Mail_RFC822->_hasUnclosedBrackets('conkergardening...', '<>')
> #2 /usr/share/grommunio-sync/lib/utils/g_RFC822.php(347): Mail_RFC822->_splitCheck(Array, ',')
> #3 /usr/share/grommunio-sync/lib/utils/g_RFC822.php(274): Mail_RFC822->_isGroup('conkergardening...')
> #4 /usr/share/grommunio-sync/lib/utils/g_RFC822.php(234): Mail_RFC822->_splitAddresses('conkergardening...')
> #5 /usr/share/grommunio-sync/lib/grommunio/mapiprovider.php(2720): Mail_RFC822->parseAddressList('conkergardening...')
> #6 /usr/share/grommunio-sync/lib/grommunio/mapiprovider.php(1697): MAPIProvider->extractEmailAddress('conkergardening...')
> #7 /usr/share/grommunio-sync/lib/grommunio/mapiprovider.php(1282): MAPIProvider->setContact(Resource id #106, Object(SyncContact))
> #8 /usr/share/grommunio-sync/lib/grommunio/importer.php(404): MAPIProvider->SetMessage(Resource id #106, Object(SyncContact))
> #9 /usr/share/grommunio-sync/lib/request/sync.php(1552): ImportChangesICS->ImportMessageChange(false, Object(SyncContact))
> #10 /usr/share/grommunio-sync/lib/request/sync.php(536): Sync->importMessage(Object(SyncParameters), Array, 'Add', Object(SyncContact), '1675017240000-0', false, false, 1)
> #11 /usr/share/grommunio-sync/lib/request/requestprocessor.php(98): Sync->Handle(0)
> #12 /usr/share/grommunio-sync/index.php(114): RequestProcessor::HandleRequest()
> #13 {main}
>   thrown (1)

**Comment by amaccuish** [comment]
Closing as also fixed here https://github.com/grommunio/grommunio-sync/commit/9b74127e2ab537c595990df586d0540c093a8270
